### ISSUE TITLE
Tales of Symphonia, freeze/hang on cutscene

### ISSUE THREAD

**Issue by NotMoreZombies** [emukidid/swiss-gc#387]
First encountered this issue on v0.5r876, tested with v0.5r878 and it is not resolved.

To give an idea of what exactly the issue looks like, the game plays entirely normally up to this cutscene:

https://www.youtube.com/watch?v=2N0Mb9h5e4I&t=14492

After the fireball is launched and the screen fades to black, it just stays black while the music keeps playing (also, the reset button stops responding).

I have tested with different ISOs (to try and eliminate the possibility of a bad rip) on GCLoader and SD2SP2. I managed to get around the issue by exporting the save to Dolphin, this file is included below (if anyone wants to reproduce the issue, just exit the building you start in and walk as far right as possible).

[AF-GQSE-TOS_000_00.zip](https://github.com/emukidid/swiss-gc/files/5084781/AF-GQSE-TOS_000_00.zip)

For some more details, I have a DOL-001 PAL console, playing the NTSC version of the game.

**Comment by Extrems** [comment]
Also happen on GC Loader as boot.iso, or with the (incomplete) disc read speed emulation enabled.

Not sure what to file this under.

**Comment by PsychoFox11** [comment]
I tried as boot.iso on my US DOL-001 NTSC and encountered no issues. I was able to reproduce the bug when loading via Swiss, both directly from the GC Loader after booting Swiss, or booting Swiss from GC Loader and then running the game from SD2SP. Thing is, there's no way to change to disc 2 when loading as boot.iso so you can't play multidisc this way. It does seem to confirm it as a Swiss thing rather than a GC Loader thing on my end though. Happy to test further if needed.

Currently with a GC Loader, if you can save past this scene, before Disc 2, you could play as boot.iso until the save after this scene, then switch to Swiss until the disc swap... and then if there are any more such bugs, go back to boot.iso on the disc. I don't know the game well enough to know if there's a save between here and Disc 2, but I'd like to know that too so I know if this is a valid workaround, I was planning to check this one out soon.

**Comment by Extrems** [comment]
How does that confirm it as a Swiss thing when it reproduced as boot.iso on my end?

**Comment by Extrems** [comment]
Also, it's fine when using the File Service Protocol and that part of the disc hasn't been cached by the server yet.
It's also fine when using a burned disc with Swiss, which shares the same code path as the GC Loader.

**Comment by PsychoFox11** [comment]
I just meant for me, and I've tried it further with no issues using it as boot.iso. It could definitely be a Swiss when a GC Loader is present. Just for me, it is only an issue when Swiss is used, but it could very well be an issue with the GC Loader working with Swiss correctly. I'd like to see it addressed, whichever side it turns up on, or if it requires the two to communicate.

It does sound like it could be the GC Loader if using a burned disc with Swiss works, or some misalignment of the two.

If you believe the GC Loader is at fault, you should definitely report this on their Github as well. If so, I'll comment my personal findings as well.

**Comment by Extrems** [comment]
It's technically the game's fault for being badly programmed.

A long seek occurs that screen fade, which happen almost instantly on most of everything else.
The disc read speed emulation doesn't currently account for seek time, which is why it has no effect.

**Comment by PsychoFox11** [comment]
Good to know. Hopefully something can be implemented to make this game fully playable, even if it is specific to this game rather than full seek time emulation. I know devs aren't always magicians though. Wonder why it works for me as boot.iso? Put it on a very new 32GB Sandisk SD (not micro) and it's been fine.

**Comment by tjanas** [comment]
I just tested it with my US DOL-001 and confirm the same behavior that @PsychoFox11 experienced; for me, it did not freeze when booting the game directly as boot.iso via GCLoader. It did freeze when launching via latest version of Swiss from my GCLoader SD card. Tested with an old SanDisk Extreme PLUS 32MB 90MB/S U3 V30 SD card.

**Comment by Extrems** [comment]
So far this is consistently reproducing on my end with a HP, a Kingston Canvas Select, and a older SanDisk Extreme as boot.iso.

**Comment by Extrems** [comment]
Video: https://www.youtube.com/watch?v=-R2ostW_9j8

**Comment by tjanas** [comment]
@Extrems is there anything you’d like me to try? I plan on testing another SD card with the game as boot.iso to see if I can make it freeze that way.

**Comment by Extrems** [comment]
I'm baffled by this issue at this point as not even accounting for seek time helped.

**Comment by tjanas** [comment]
I just tried a MicroCenter branded 32GB micro sd card, and that DID have the issue running as GCLoader boot.iso.

**Comment by PsychoFox11** [comment]
Are you using a full .iso on an nkit.iso for the boot.iso? I don't think it would matter unless that could affect seek time things. I am using an nkit.iso - I can restore it to the full redump iso it started as and try that if it would help anything. All of my tests were with nkit.iso images.

**Comment by tjanas** [comment]
My main GCLoader sd card is using nkit. For the two test sd cards I used with booting the game via boot.iso (one had the issue and one didn’t), I used the redump iso.

**Comment by Extrems** [comment]
Verbatim DVD+R on Disc Drive 08 2002/23 (61)
```
address 0064A940 length 00008800 offset 39B3D478 ticks 00415D57
address 0064A940 length 00008800 offset 39B48478 ticks 0002BF0A
address 0064A940 length 00008800 offset 39B54C78 ticks 0002AE82
address 0064A940 length 00008800 offset 39B65478 ticks 0002D23C
address 0064A940 length 00008800 offset 39B6FC78 ticks 0002C997
address 0064A940 length 00008800 offset 39B80478 ticks 0002A2F0
address 0064A940 length 00008800 offset 39B8E478 ticks 00029A0A
address 0064A940 length 00008800 offset 39B98C78 ticks 0002AE10
address 0064A940 length 00004000 offset 39BA9C78 ticks 0001C3A6
[fade out]
address 012BC980 length 000025A0 offset 13B1EC20 ticks 004A6CC5
address 012BC980 length 000025A0 offset 13B1EC20 ticks 0035A9A7
[fade in]
effect person delete
address 0064A940 length 00003800 offset 39BADC78 ticks 00513BB6
```
SanDisk Extreme on GC Loader
```
address 0064A940 length 00008800 offset 39B3D478 ticks 0002EC28
address 0064A940 length 00008800 offset 39B48478 ticks 0002FE80
address 0064A940 length 00008800 offset 39B54C78 ticks 0002DAC7
address 0064A940 length 00008800 offset 39B65478 ticks 0002F1A4
address 0064A940 length 00008800 offset 39B6FC78 ticks 00031624
address 0064A940 length 00008800 offset 39B80478 ticks 0002E9F0
address 0064A940 length 00008800 offset 39B8E478 ticks 0002D65B
address 0064A940 length 00008800 offset 39B98C78 ticks 0002DC52
address 0064A940 length 00004000 offset 39BA9C78 ticks 00016D15
[fade out]
address 012BC980 length 000025A0 offset 13B1EC20 ticks 0000C249
address 012BC980 length 000025A0 offset 13B1EC20 ticks 0000FBEE
```
SanDisk Extreme on GC Loader with Emulate Read Speed (Swiss v0.5r890)
```
address 0064A940 length 00008800 offset 39B3D478 ticks 0034FE31
address 0064A940 length 00008800 offset 39B48478 ticks 0015D326
address 0064A940 length 00008800 offset 39B54C78 ticks 0015D35B
address 0064A940 length 00008800 offset 39B65478 ticks 0015D48A
address 0064A940 length 00008800 offset 39B6FC78 ticks 0015D2A5
address 0064A940 length 00008800 offset 39B80478 ticks 0015D4CD
address 0064A940 length 00008800 offset 39B8E478 ticks 0015D403
address 0064A940 length 00008800 offset 39B98C78 ticks 0015D2E7
address 0064A940 length 00004000 offset 39BA9C78 ticks 0015D47D
[fade out]
address 012BC980 length 000025A0 offset 13B1EC20 ticks 00400C5A
address 012BC980 length 000025A0 offset 13B1EC20 ticks 001A75A5
```

**Comment by Extrems** [comment]
Fixed in d46fd2a (r905) for GC Loader with Emulate Read Speed enabled.

**Comment by Extrems** [comment]
SanDisk Extreme on GC Loader with Emulate Read Speed (Swiss v0.5r905)
```
address 0064A940 length 00008800 offset 39B3D478 ticks 004D89E6
address 0064A940 length 00008800 offset 39B48478 ticks 0003085E
address 0064A940 length 00008800 offset 39B54C78 ticks 0002DF7F
address 0064A940 length 00008800 offset 39B65478 ticks 0002F8A8
address 0064A940 length 00008800 offset 39B6FC78 ticks 00031E2B
address 0064A940 length 00008800 offset 39B80478 ticks 0002F30E
address 0064A940 length 00008800 offset 39B8E478 ticks 0002DD44
address 0064A940 length 00008800 offset 39B98C78 ticks 0002E096
address 0064A940 length 00004000 offset 39BA9C78 ticks 00016D67
[fade out]
address 012BC980 length 000025A0 offset 13B1EC20 ticks 0043A6CF
address 012BC980 length 000025A0 offset 13B1EC20 ticks 002F5663
[fade in]
effect person delete
address 0064A940 length 00003800 offset 39BADC78 ticks 0056D411
```

**Comment by tjanas** [comment]
Just tested this with Swiss v0.5r906 and still experiencing the same issue. I have Emulate Read Speed enabled with GCLoader.

**Comment by tjanas** [comment]
Also, I’m experiencing a new issue with r906 that I didn’t with r888: when starting up Paper Mario (nkit iso) with Emulate Read Speed enabled, I get a disc read error. No error when this option is disabled. Also, when the error occurs, pressing reset on the GameCube allows it to boot without an error.
![04AA263A-8EBE-467E-9F5C-4D6BD4DF57E7](https://user-images.githubusercontent.com/20304619/92427475-365e8d80-f152-11ea-8b7b-93eeb34c2297.jpeg)

**Comment by Extrems** [comment]
Well, I'm burned out from this. I guess it just isn't getting fixed.

**Comment by tjanas** [comment]
> Well, I'm burned out from this. I guess it just isn't getting fixed.

So I tried disabling Boot with IPL, and that makes the bug go away with r906.

**Comment by Extrems** [comment]
If you booted using the other disc, only the initial disc is currently patched.

**Comment by PsychoFox11** [comment]
> > Well, I'm burned out from this. I guess it just isn't getting fixed.
> 
> So I tried disabling Boot with IPL, and that makes the bug go away with r906.

I already had Boot with IPL disabled, and it made no difference for me in r912. However, I can still run this segment consistently when using it as boot.iso on my GC Loader, from a 32GB Sandisk SD (not micro) card. I keep a few files I rotate as boot.iso on there, and I even copied them all off and back on to put it in a different position on the card, still no issues using that method. I'm using an nkit.iso as boot.iso by the way, haven't tested regular iso. I have an SD2SP2 so I'm applying patches, but only the defaults, when testing with Swiss which does have the issue.

Won't keep this thread alive after this comment since it is dead for now, but it's worth a try if using GC Loader, it seems to work for some. Once you get past this scene, save and switch over to Swiss before the disc change (I haven't played the full game yet, hoping there is a save between here and the disc change!).

**Comment by Extrems** [comment]
>I have an SD2SP2 so I'm applying patches, but only the defaults, when testing with Swiss which does have the issue.
You must enable the Emulate Read Speed option, otherwise of course the issue will persist.

The issue with boot through IPL has been fixed.

**Comment by PsychoFox11** [comment]
Ah ok, pretty new to Swiss and thought it would enable it within the default patches if it was needed for a certain game. I'll just keep it on in general, seems to help with all my other ODE devices that offer it. Thanks for the info!

**Comment by Extrems** [comment]
This was kept open because other devices are affected as well, such as passive SD card adapters.
