### ISSUE TITLE
Tony Hawk's American Wasteland and Splinter Cell Chaos Theory doesn't boot.

### ISSUE THREAD

**Issue by egarjanis** [emukidid/swiss-gc#479]
Hi!
This might be a tough one, because I asked on Reddit for someone to confirm this for me and on their console both of these games boot fine.

Things I did:
- Verified rips using redump.org - file directly on SD card
- Tried three different SD cards
- Tried booting from SD2SP2 as well as GC-Loader and Gecko
- Tried default settings, video patches disabled, IPL boot, everything I could think of

More info:
- Both games are US NTSC ISOs, though I tried Chaos Theory PAL too, same thing.
- My console is NTSC-J.
- Using Swiss v0.5r1026
- American Wasteland reboots into BIOS screen. Chaos Theory stays with back screen until restart.

![newnewnew](https://user-images.githubusercontent.com/8227665/108992838-6a971d80-76a2-11eb-8b96-c21e3371d901.png)

**Comment by Extrems** [comment]
I couldn't reproduce the issue with Tom Clancy's Splinter Cell: Chaos Theory, but there's indeed something with Tony Hawk's American Wasteland.

**Comment by egarjanis** [comment]
> 
> 
> I couldn't reproduce the issue with Tom Clancy's Splinter Cell: Chaos Theory, but there's indeed something with Tony Hawk's American Wasteland.

I got Chaos Theory to run, I think I screwed up somewhere before. I had to force enable 480i.

I guess "No" in "Force Video Mode" makes it so game uses whatever setting is for "Default Game Setting"?
Enabling "Disable Video Patches" makes the game not run for me also. 480p forced is not working for me either, but the game should support it.
Sorry, I'm a bit new to GameCube scene and using Swiss.

But I guess it's a different issue entirely, sorry for lumping these games/issues together. Though they were similar issues. I know this can be quite annoying. Sorry!

**Comment by Extrems** [comment]
I force 480p by default, which worked.

**Comment by egarjanis** [comment]
> 
> 
> I force 480p by default, which worked. "No" is the game's original behavior.

Weird, no dice for me. "No" or "480p" just doesn't work on my end. Forced 480i does. I guess at least it runs.

Thank you for your responses and good luck fixing American Wasteland! If I can be of any help, let me know.

**Comment by egarjanis** [comment]
Update on SCCT. There's some other guy on Reddit that reports same weird behavior with his NTSC-J console. Forcing 480i and 240p let's the game boot fine, 480p or leaving default makes game not work.

**Comment by Extrems** [comment]
If you press A twice on the black screen, you can proceed. It's the progressive scan prompt failing to render text.

**Comment by Extrems** [comment]
Tom Clancy's Splinter Cell: Chaos Theory issue fixed in e416ecf (r1045).

**Comment by egarjanis** [comment]
> 
> 
> If you press A twice on the black screen, you can proceed. It's the progressive scan prompt failing to render text.

Just tested it, can confirm that works. So it is a NTSC-J thing?

**Comment by method-games** [comment]
I'm experiencing the same issue with Tony Hawk American Wasteland on an NTSC-J console. Using Swiss v0.5r1047. Switching forced resolution settings does not seem to resolve the issue in my case. Can confirm game worked with earlier Swiss revision v0.5r990

**Comment by Extrems** [comment]
I've never stated Tony Hawk's American Wasteland had been fixed.

**Comment by method-games** [comment]
I understand that. Others have reported that forcing certain resolution settings can remedy the issue. I am reporting that none of the resolution settings work in my case.

**Comment by Extrems** [comment]
It does not remedy the issue for Tony Hawk's American Wasteland. It remedied the issue for Tom Clancy's Splinter Cell: Chaos Theory.

**Comment by method-games** [comment]
My apologies. Thank you for the clarification.

**Comment by Extrems** [comment]
Tony Hawk's American Wasteland issue fixed in b1671b7 (r1049).
