### ISSUE TITLE
change disc is broken in swiss v0.6

### ISSUE THREAD

**Issue by azareth012** [emukidid/swiss-gc#621]
disc swap is broken in swiss 0.6!

**Comment by Extrems** [comment]
Can you be more specific?

**Comment by azareth012** [comment]
> Can you be more specific?

Swiss stopped recognizing disk 2 in all games, I have tried with MGS, Killer 7, RE0, 1, 4, Veronica and it happens the same, with swiss 0.5 this does not happen, so I went back to version 0.5 and works

**Comment by Bakuku** [comment]
I just played REmake and second disc does work for me.

- PAL Gamecube
- Wiikey Fusion

**Comment by Extrems** [comment]
I'm guessing you're using a Nintendont-style folder structure. Is this correct?

**Comment by azareth012** [comment]
> I'm guessing you're using a Nintendont-style folder structure. Is this correct?

correct, with swiss 0.5 everything works fine, when updating to 0.6 the disk change stops working, so go back to 0.5

**Comment by azareth012** [comment]
> I just played REmake and second disc does work for me.
> 
> * PAL Gamecube
> * Wiikey Fusion

In the game disc change menu, does it automatically change to disc 2? in my case the automatic disk change stopped working in 0.6, if I return to 0.5 it works again

**Comment by Extrems** [comment]
Fixed in 4b381a3 (r1226).

**Comment by azareth012** [comment]
> Fixed in [4b381a3](https://github.com/emukidid/swiss-gc/commit/4b381a3b75fe4c41bd27d58af58b89785d4d5675) (r1226).

I tried with Swiss v0.6r1215 and Swiss v0.6r1216 and the problem persists, in Swiss v0.5r1196 the disc change works correctly for me

**Comment by Extrems** [comment]
This is a regression from a change made in 2263e3d to avoid issue #608. It's been fixed for the next release.
