### ISSUE TITLE
[Feature request]: Option to switch to 448i prior to game boot

### ISSUE THREAD

**Issue by rabscootle** [emukidid/swiss-gc#804]
### Describe the feature

Hi!

I was wondering if there was any chance that Swiss could receive an option to automatically switch to 640x448i prior to loading a selected game with "Boot through IPL" enabled.

Carby/GCVideo currently misses most of the GC boot animation due to the resolution change (even if you force it to 480i since it's not the same resolution). By setting it before leaving Swiss UI this would possibly fix the issue (as boot animation to game works fine if resolution is not overridden and game resolution is also 448i)?

If implemented, having it be usable as a per-game setting would also allow for it to be enabled on just games that natively support 480p (so resolution can be switched back for those games once boot animation is complete), so games that don't aren't stuck on interlaced after boot.

**Comment by Extrems** [comment]
This is already addressed by the "Pause for resolution change" option, although I'm not sure why you're talking about interlaced video to begin with.

**Comment by rabscootle** [comment]
Sorry, should have mentioned that in the original post.  "Pause for resolution change" doesn't seem to fix it entirely, some of the initial audio and video is still cut off. Maybe an option to increase the delay slightly would fix it?

For reference I'm using a GCLoader and Carby.

**Comment by Extrems** [comment]
The delay is indeed display dependent. It looks like you got a worse deal than average.

**Comment by rabscootle** [comment]
Ah... That would explain it.

**Comment by Extrems** [comment]
Also, I think you got NTSC Revision 1.0 as IPL. You can put a dump of any newer revision under `/swiss/patches/ipl.bin` on the patch device and 480p should work then.

**Comment by rabscootle** [comment]
I'll look into it. Thanks

**Comment by rabscootle** [comment]
...possibly a bad place to ask but is there any way to force Swiss to be 448p? I've managed to force progressive to the boot animation but there is still issues due to the minimal resolution change. Not a huge issue at this point but definitely wanted to ask before closing the ticket.

**Comment by rabscootle** [comment]
Nevermind! I'll live with the current behavior; The issue is almost non-existent now.

Thanks for your help :)
